user  www www;
worker_processes  auto;
worker_rlimit_nofile  65535;

error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;

events {
	use  epoll;
	worker_connections  65535;
	multi_accept  on;
}

http {
	include       mime.types;
	default_type  application/octet-stream;
	charset       utf-8;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
					  '$status $body_bytes_sent "$http_referer" '
					  '"$http_user_agent" "$http_x_forwarded_for"';
	
	#access_log  /www/logs/nginx/access.log  main;
	#error_log  /www/logs/nginx/error.log  crit;

	access_log off;	
	error_log  /www/logs/nginx/error.log  warn;

	sendfile       on;
	tcp_nopush     on;	
	tcp_nodelay    on;
	server_tokens  off;
	
	keepalive_timeout  60;
	client_body_timeout  60;
	reset_timedout_connection  on;
	send_timeout  60;
	
	server_names_hash_bucket_size 128; 
	client_header_buffer_size 16k;	
	large_client_header_buffers 4 32k;
	client_max_body_size 8m;

	proxy_temp_path   /www/cache/nginx_proxy_temp;
	proxy_cache_path  /www/cache/nginx_proxy_cache levels=1:2 keys_zone=nginx_cache:50m inactive=1d max_size=1g;

	client_body_buffer_size  512k;
	proxy_connect_timeout    60;
	proxy_read_timeout       60;
	proxy_send_timeout       60;
	proxy_buffer_size        32k;
	proxy_buffers           4 64k;
	proxy_busy_buffers_size 128k;
	proxy_temp_file_write_size 128k;
	proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_404;
	proxy_cache nginx_cache;

	gzip  on;
	gzip_disable  "msie6";
	gzip_min_length  1k;	
	gzip_comp_level 2;
	gzip_proxied  any;
	gzip_buffers  4  16k; 
	gzip_http_version  1.1;	
	gzip_types  text/plain text/css text/javascript application/x-javascript;
	gzip_vary  on;

	upstream myhost {
		ip_hash;
		server 192.168.1.101 weight=1 max_fails=2 fail_timeout=30s;
	}

	server {
		listen 80;
		server_name localhost;
		index  index.html index.php;
		root   /www/htdocs/default;

		location / {
			proxy_pass http://myhost;

			proxy_redirect off;

			proxy_set_header   Host             $host;
			proxy_set_header   X-Real-IP        $remote_addr;
			proxy_set_header   REMOTE-HOST      $remote_addr;
			proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
			proxy_pass_header  User-Agent;
		}

		location ~ /purge(/.*) {
			allow   127.0.0.1;
			allow   192.168.1.151;
			deny    all;
			proxy_cache_purge   nginx_cache   $host$1$is_args$args;
		}

		location ~ .*\.(jpg|gif|png|js|css|jpeg|html|swf|bmp)$ {
			proxy_pass http://myhost;

			proxy_cache_key    $host$uri$is_args$args;
			proxy_set_header   Host             $host;
			proxy_set_header   X-Real-IP        $remote_addr;
			proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
			proxy_cache_valid  200 304 12h;

			expires 24h;
			proxy_ignore_headers "Cache-Control" "Expires" "Set-Cookie";
		}

		#error_page  403  https://www.baidu.com/403;

		access_log off;
	}
	
	#VirtualHost
	#include /usr/local/nginx/domains/*.conf;
}
