[global]
rlimit_files = 65535
daemonize = yes

[www]
user = www
group = www
listen = 127.0.0.1:9000

pm = dynamic
pm.max_children = 128
pm.start_servers = 32
pm.min_spare_servers = 32
pm.max_spare_servers = 128

rlimit_files = 65535
request_slowlog_timeout = 30s
slowlog = /data/logs/php/slowlog.log
