uid = nobody
gid = nobody
port = 873
use chroot = yes
max connections = 100
pid file = /usr/local/rsync/var/run/rsyncd.pid
log file = /data/logs/rsync/rsyncd.log
list = no
strict modes = no
secrets file = /usr/local/rsync/etc/rsyncd.pass
#ignore errors

#hosts allow = IP address
hosts deny=*

#[demo]
#uid = root
#gid = root
#path = /rsync module path
#auth users = username

#read only = no 
